"""
aggregator.py — Orchestrator Tool (v2)
Merges all specialist ratings + benchmarks + redlines + compromises into:
  - scorecard.json        (flat list, backward compat)
  - buyer_view.json       (2D risk map sorted by impact)
  - vendor_view.json      (Red/Amber only, sorted by likelihood)
  - scorecard.html        (Red/Amber/Green colour-coded table)
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# 2D Risk Score Lookup  rule_id → (likelihood 1-10, impact 1-10)
# Amber = base * 0.70, Green = (2, 2), N/A = (1, 1)
# ---------------------------------------------------------------------------
_RISK: dict[str, dict[str, tuple[int, int]]] = {
    "legal_agent": {
        "R1": (8, 9), "R2": (7, 9), "R3": (6, 6),
        "R4": (5, 7), "R5": (4, 6), "R6": (5, 5),
    },
    "data_privacy_agent": {
        "R1": (7, 10), "R2": (6, 9), "R3": (5, 6),
        "R4": (6, 8),  "R5": (7, 8), "R6": (5, 6), "R7": (6, 7),
    },
    "commercial_agent": {
        "R1": (7, 5), "R2": (6, 4), "R3": (8, 8),
        "R4": (7, 8), "R5": (6, 5), "R6": (5, 9),
    },
}
_DEFAULT_SCORE = (4, 4)

# Vendor-perspective: which rules represent concessions from vendor
_VENDOR_RULES = {
    "legal_agent":         {"R1", "R2", "R5", "R6"},
    "data_privacy_agent":  {"R1", "R2", "R4", "R5", "R6", "R7"},
    "commercial_agent":    {"R3", "R4", "R6"},
}


def _risk_coords(agent: str, rule_id: str, rating: str) -> tuple[int, int]:
    base = _RISK.get(agent, {}).get(rule_id, _DEFAULT_SCORE)
    if rating == "Green" or rule_id == "N/A":
        return (2, 2)
    if rating == "Amber":
        return (max(1, round(base[0] * 0.70)), max(1, round(base[1] * 0.70)))
    return base  # Red


# ---------------------------------------------------------------------------
# HTML renderer (unchanged aesthetic from v1)
# ---------------------------------------------------------------------------
_COLORS = {"Red": "#dc2626", "Amber": "#d97706", "Green": "#16a34a"}
_BG     = {"Red": "#fde8e8", "Amber": "#fef9c3", "Green": "#dcfce7"}
_EMOJI  = {"Red": "🔴", "Amber": "🟡", "Green": "🟢"}

_HTML = """\
<!DOCTYPE html><html lang="en"><head>
<meta charset="UTF-8"><title>Compliance Sentinel — Scorecard</title>
<style>
*{{box-sizing:border-box}}
body{{font-family:-apple-system,sans-serif;background:#0f172a;color:#e2e8f0;margin:0;padding:2rem}}
h1{{font-size:1.75rem;font-weight:700;color:#f8fafc;margin-bottom:.25rem}}
.sub{{color:#94a3b8;font-size:.875rem;margin-bottom:2rem}}
.stats{{display:flex;gap:1rem;flex-wrap:wrap;margin-bottom:2rem}}
.stat{{background:#1e293b;border:1px solid #334155;border-radius:.75rem;padding:1rem 1.5rem;text-align:center;min-width:120px}}
.stat-n{{font-size:2rem;font-weight:800;line-height:1}}
.stat-l{{font-size:.75rem;color:#94a3b8;margin-top:.25rem}}
.red{{color:#f87171}}.amber{{color:#fbbf24}}.green{{color:#4ade80}}
table{{width:100%;border-collapse:collapse;background:#1e293b;border-radius:.75rem;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,.4)}}
thead tr{{background:#0f172a}}
th{{padding:.75rem 1rem;text-align:left;font-size:.7rem;text-transform:uppercase;letter-spacing:.08em;color:#64748b;border-bottom:1px solid #334155}}
td{{padding:.75rem 1rem;font-size:.8rem;border-bottom:1px solid #1e293b;vertical-align:top}}
tr:last-child td{{border-bottom:none}}
tr:hover td{{background:#263248}}
.badge{{display:inline-block;padding:.2rem .6rem;border-radius:9999px;font-size:.72rem;font-weight:700;color:#fff}}
.agent{{display:inline-block;padding:.15rem .45rem;background:#334155;border-radius:.375rem;font-size:.68rem;color:#94a3b8;font-family:monospace}}
.rule{{font-family:monospace;color:#a78bfa;font-size:.78rem}}
.bench{{font-size:.7rem;padding:.15rem .4rem;border-radius:.3rem;font-weight:600}}
.bench-agg{{background:#7f1d1d;color:#fca5a5}}.bench-std{{background:#1e3a5f;color:#93c5fd}}.bench-len{{background:#14532d;color:#86efac}}
pre{{background:#0f172a;padding:.5rem;border-radius:.375rem;font-size:.7rem;white-space:pre-wrap;word-break:break-word;color:#94a3b8;max-height:80px;overflow:auto;margin:0}}
</style></head><body>
<h1>⚖️ Compliance Sentinel</h1>
<p class="sub">SaaS DPA Risk Scorecard &mdash; GDPR + CCPA/CPRA &bull; Generated by AI Swarm</p>
<div class="stats">
  <div class="stat"><div class="stat-n">{total}</div><div class="stat-l">Total</div></div>
  <div class="stat"><div class="stat-n red">{red}</div><div class="stat-l">🔴 Red</div></div>
  <div class="stat"><div class="stat-n amber">{amber}</div><div class="stat-l">🟡 Amber</div></div>
  <div class="stat"><div class="stat-n green">{green}</div><div class="stat-l">🟢 Green</div></div>
</div>
<table><thead><tr>
  <th>Clause</th><th>Agent</th><th>Rating</th><th>Rule</th><th>Benchmark</th><th>Reason / Redline</th>
</tr></thead><tbody>
{rows}
</tbody></table>
</body></html>"""


def _html_row(e: dict) -> str:
    rating = e.get("rating", "Green")
    bench  = e.get("benchmark_verdict", "")
    bench_cls = {"aggressive": "bench-agg", "standard": "bench-std",
                 "lenient": "bench-len"}.get(bench, "")
    redline = e.get("suggested_redline", "")
    redline_html = f"<br><pre>✏ {redline[:180]}</pre>" if redline and "unavailable" not in redline else ""
    bg     = _BG.get(rating, "transparent")
    color  = _COLORS.get(rating, "#64748b")
    emoji  = _EMOJI.get(rating, "")
    cid    = e.get("clause_id", "")
    agent  = e.get("agent_source", "")
    rule   = e.get("rule_id", "N/A")
    reason = e.get("reason", "")
    bench_tag = f'<span class="bench {bench_cls}">{bench}</span>' if bench else "—"
    return (
        f'<tr style="background:{bg}">'
        f'<td><strong>{cid}</strong></td>'
        f'<td><span class="agent">{agent}</span></td>'
        f'<td><span class="badge" style="background:{color}">{emoji} {rating}</span></td>'
        f'<td><span class="rule">{rule}</span></td>'
        f'<td>{bench_tag}</td>'
        f'<td>{reason}{redline_html}</td>'
        f'</tr>'
    )


# ---------------------------------------------------------------------------
# Main aggregate function
# ---------------------------------------------------------------------------

def aggregate(
    responses: list[dict[str, Any]],
    benchmarks: dict[str, dict] | None = None,
    redlines: dict[str, dict] | None = None,
    compromises: dict[str, list] | None = None,
    contract_id: str = "default",
    output_dir: str = ".",
    output_html: str | None = None,
    output_json: str | None = None,
) -> dict[str, Any]:
    """
    Merge all data into risk map entries + buyer/vendor views.

    Args:
        responses:   List of {clause_id, agent, rating, rule_id, reason} from specialist agents.
        benchmarks:  Dict clause_id → benchmark_clause() result.
        redlines:    Dict clause_id → generate_redline() result.
        compromises: Dict clause_id → list of propose_compromise() results.
        contract_id: Identifier for this contract run.
        output_dir:  Directory to write output files.
    """
    benchmarks  = benchmarks  or {}
    redlines    = redlines    or {}
    compromises = compromises or {}

    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    # Validate + normalise responses
    clean: list[dict] = []
    for r in responses:
        if not isinstance(r, dict):
            continue
        rating  = r.get("rating", "Green")
        if rating not in ("Red", "Amber", "Green"):
            rating = "Green"
        agent   = str(r.get("agent", "unknown"))
        rule_id = str(r.get("rule_id", "N/A"))
        cid     = str(r.get("clause_id", "?"))

        x, y = _risk_coords(agent, rule_id, rating)
        bench = benchmarks.get(cid, {})
        redl  = redlines.get(cid, {})

        entry: dict[str, Any] = {
            "clause_id":         cid,
            "agent_source":      agent,
            "rating":            rating,
            "rule_id":           rule_id,
            "reason":            str(r.get("reason", "")),
            "x_likelihood":      x,
            "y_impact":          y,
            "benchmark_verdict": bench.get("benchmark_verdict", ""),
            "comparison_note":   bench.get("comparison_note", ""),
            "area":              bench.get("area", ""),
            "suggested_redline": redl.get("suggested_redline", ""),
            "rule_id_addressed": redl.get("rule_id_addressed", ""),
            "compromise_options": compromises.get(cid, []),
        }
        clean.append(entry)

    # Sort: clause numerically then agent
    def _key(e: dict) -> tuple:
        parts = e["clause_id"].replace("_", ".").split(".")
        num = []
        for p in parts:
            try: num.append(int(p))
            except ValueError: num.append(p)
        return (num, e["agent_source"])

    clean.sort(key=_key)

    red   = sum(1 for e in clean if e["rating"] == "Red")
    amber = sum(1 for e in clean if e["rating"] == "Amber")
    green = sum(1 for e in clean if e["rating"] == "Green")

    # --- scorecard.json (flat, backward compat)
    sc_path = out / (output_json or "scorecard.json")
    sc_path.write_text(json.dumps(clean, indent=2), encoding="utf-8")

    # --- buyer_view.json: all entries, highest impact first
    buyer = sorted(clean, key=lambda e: (-e["y_impact"], -e["x_likelihood"]))
    (out / "buyer_view.json").write_text(
        json.dumps({
            "contract_id": contract_id,
            "perspective": "buyer",
            "description": "Sorted by compliance impact — address highest-impact risks first.",
            "risk_map": buyer,
            "summary": {"total": len(clean), "red": red, "amber": amber, "green": green},
        }, indent=2),
        encoding="utf-8",
    )

    # --- vendor_view.json: Red+Amber only, sorted by likelihood (deal blockers first)
    vendor_entries = [e for e in clean if e["rating"] in ("Red", "Amber")]
    vendor = sorted(
        vendor_entries,
        key=lambda e: (
            -e["x_likelihood"],
            0 if _VENDOR_RULES.get(e["agent_source"], set()) & {e["rule_id"]} else 1,
        ),
    )
    (out / "vendor_view.json").write_text(
        json.dumps({
            "contract_id": contract_id,
            "perspective": "vendor",
            "description": "Clauses requiring vendor concession, sorted by deal-blocking likelihood.",
            "risk_map": vendor,
            "summary": {"total": len(vendor_entries), "red": red, "amber": amber},
        }, indent=2),
        encoding="utf-8",
    )

    # --- scorecard.html
    rows = "\n".join(_html_row(e) for e in clean)
    html = _HTML.format(total=len(clean), red=red, amber=amber, green=green, rows=rows)
    html_path = out / (output_html or "scorecard.html")
    html_path.write_text(html, encoding="utf-8")

    return {
        "scorecard":   clean,
        "summary":     {"total": len(clean), "red": red, "amber": amber, "green": green},
        "html_path":   str(html_path.resolve()),
        "json_path":   str(sc_path.resolve()),
        "buyer_path":  str((out / "buyer_view.json").resolve()),
        "vendor_path": str((out / "vendor_view.json").resolve()),
        "contract_id": contract_id,
    }
